// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ueXPlBtpgUj-CJVhCDS2JW_WYn9gExY',
    appId: '1:336241483230:web:7484791f9fdecb459d914f',
    messagingSenderId: '336241483230',
    projectId: 'tunalink-auth-2',
    authDomain: 'tunalink-auth-2.firebaseapp.com',
    storageBucket: 'tunalink-auth-2.firebasestorage.app',
    measurementId: 'G-W2VGW03LD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBJ7pixsKWjKxaRRFeYyB3USyzWBPwEl8',
    appId: '1:336241483230:android:5790ea623c6fdce09d914f',
    messagingSenderId: '336241483230',
    projectId: 'tunalink-auth-2',
    storageBucket: 'tunalink-auth-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ4EWBPSQPwqBTJtUm9ut9nfzPZj17uuo',
    appId: '1:336241483230:ios:92c60012b449c8539d914f',
    messagingSenderId: '336241483230',
    projectId: 'tunalink-auth-2',
    storageBucket: 'tunalink-auth-2.firebasestorage.app',
    iosBundleId: 'com.example.tunalink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ4EWBPSQPwqBTJtUm9ut9nfzPZj17uuo',
    appId: '1:336241483230:ios:92c60012b449c8539d914f',
    messagingSenderId: '336241483230',
    projectId: 'tunalink-auth-2',
    storageBucket: 'tunalink-auth-2.firebasestorage.app',
    iosBundleId: 'com.example.tunalink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ueXPlBtpgUj-CJVhCDS2JW_WYn9gExY',
    appId: '1:336241483230:web:f7162a432ee1c86a9d914f',
    messagingSenderId: '336241483230',
    projectId: 'tunalink-auth-2',
    authDomain: 'tunalink-auth-2.firebaseapp.com',
    storageBucket: 'tunalink-auth-2.firebasestorage.app',
    measurementId: 'G-16P51NNPJY',
  );
}
